blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/BayBreezy/strapi-plugin-gen-types/discussions
    about: Ask questions and discuss ideas with the community
  - name: Strapi Community Discord
    url: https://discord.strapi.io/
    about: Get help from the Strapi community
